id: P007069
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ9154
  title: སྐལ་ལྡན་རྒྱ་མཚོའི་མགུར་འབུམ།
  author: ''
  volumes:
    46f51424ae374a5fb8c5bf77d558bbf7:
      image_group_id: I1KG14881
      title: ''
      volume_number: 1
      total_pages: 378
ebook_metadata:
  title: སྐལ་ལྡན་རྒྱ་མཚོའི་མགུར་འབུམ།
  author: ''
  sku: P007069
  cover: cover.jpg
  layers:
  - pagination
