id: P007069
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ9154
  title: སྐལ་ལྡན་རྒྱ་མཚོའི་མགུར་འབུམ།
  author: ''
  volumes:
    32d0e7fadfb64fa98cfaca74483719e7:
      image_group_id: I1KG14881
      title: Volume 1 of skal ldan rgya mtsho'i mgur 'bum/
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
ebook_metadata:
  title: སྐལ་ལྡན་རྒྱ་མཚོའི་མགུར་འབུམ།
  author: ''
  sku: P007069
  cover: cover.jpg
  layers:
  - pagination
