id: P007069
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ9154
  title: སྐལ་ལྡན་རྒྱ་མཚོའི་མགུར་འབུམ།
  author: ''
  volumes:
    32d0e7fadfb64fa98cfaca74483719e7:
      image_group_id: I1KG14881
      title: Volume 1 of skal ldan rgya mtsho'i mgur 'bum/
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
